name: Trigger Satis Build

on:
  release:
    types:
      - created

jobs:
  webhook:
    name: Send Webhook
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Set Package
        id: package
        env:
          REPO: ${{ github.repository }}
        run: echo ::set-output name=PACKAGE::${REPO##*/}

      - name: Set Version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WEBHOOK_TOKEN }}
          repository: wpscholar/satis
          event-type: 'Trigger Satis Build'
          client-payload: >-
            {
              "vendor": "${{ github.repository_owner }}",
              "package": "${{ steps.package.outputs.PACKAGE }}",
              "version": "${{ steps.tag.outputs.VERSION }}"
            }
