name: Build Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    name: On Push to Main
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Setup Workflow Context
        id: workflow
        working-directory: ${{ runner.temp }}
        env:
          REPO: ${{ github.repository }}
        run: |
          mkdir dist
          echo ::set-output name=DIST::${PWD}/dist
          echo ::set-output name=PACKAGE::${REPO##*/}

      - name: PHP version
        run: php --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer vendor directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        run: composer install --no-progress --no-dev

      - name: Prepare files
        run: rsync -r --exclude-from=.distignore . ${{ steps.workflow.outputs.DIST }}

      - name: List Files
        working-directory: ${{ steps.workflow.outputs.DIST }}
        run: find .

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.workflow.outputs.PACKAGE }}
          path: ${{ steps.workflow.outputs.DIST }}
